Hypothesis Artifacts Update
Former-commit-id: 3b33e42c633e552dffd6257d3b705eb79fc226fb

diff --git a/.github/workflows/test-frontend-numpy.yml b/.github/workflows/test-frontend-numpy.yml
--- a/.github/workflows/test-frontend-numpy.yml
+++ b/.github/workflows/test-frontend-numpy.yml
@@ -1,5 +1,5 @@
 name: test-frontend-numpy
-on: [push, pull_request]
+on: [push, pull_request, workflow_dispatch]
 jobs:
   run-nightly-tests:
     runs-on: ubuntu-latest
@@ -11,15 +11,41 @@ jobs:
           persist-credentials: false
           submodules: "recursive"
 
-      - name: Cache hypothesis
-        uses: actions/cache@v3
-        with:
-          path: |
-            ivy/.hypothesis
-          key: ${{ runner.os }}-hypothesis
+#      - name: Download artifact
+#        uses: dawidd6/action-download-artifact@v2
+#        with:
+#          workflow: test-frontend-numpy.yml
+#          workflow_conclusion: completed
+#          name: hypothesis_frontend_numpy_zip
+#          path: |
+#            ivy/.hypothesis/
+#
+#      - name: Unzip Hypothesis Examples
+#        run: |
+#          cd ivy/.hypothesis
+#          unzip examples.zip
+#          rm examples.zip
 
       - name: Run Frontend Tests
+        id: tests
         run: |
           cd ivy
           mkdir -p .hypothesis
           docker run --rm -v `pwd`:/ivy -v `pwd`/.hypothesis:/.hypothesis unifyai/ivy:latest python3 -m pytest --backend numpy ivy/ivy_tests/test_ivy/test_frontends/test_numpy
+        continue-on-error: true
+
+      - name: Zip Hypothesis Examples
+        run: |
+          cd ivy/.hypothesis
+          zip -r examples.zip examples
+
+      - name: Upload hypothesis
+        uses: actions/upload-artifact@v3
+        with:
+          name: hypothesis_frontend_numpy_zip
+          path: |
+            ivy/.hypothesis/examples.zip
+
+#      - name: Check on failures
+#        if: steps.tests.outcome != 'success'
+#        run: exit 1
