Hypothesis Artifacts Update

diff --git a/.github/workflows/test-ivy-stateful.yml b/.github/workflows/test-ivy-stateful.yml
--- a/.github/workflows/test-ivy-stateful.yml
+++ b/.github/workflows/test-ivy-stateful.yml
@@ -22,16 +22,44 @@ jobs:
            persist-credentials: false
            submodules: "recursive"
 
-       - name: Cache hypothesis
-         uses: actions/cache@v3
-         with:
-           path: |
-             ivy/.hypothesis
-           key: ${{ runner.os }}-hypothesis
+#       - name: Download artifact
+#         uses: dawidd6/action-download-artifact@v2
+#         with:
+#           workflow: test-ivy-stateful.yml
+#           workflow_conclusion: completed
+#           name: hypothesis_${{ matrix.backends }}_${{ matrix.submodules }}_zip
+#           path: |
+#             ivy/.hypothesis/
+#
+#       - name: Unzip Hypothesis Examples
+#         run: |
+#           cd ivy/.hypothesis
+#           unzip examples.zip
+#           rm examples.zip
+
 
        - name: Run Stateful Tests
          id: tests
          run: |
            cd ivy
            mkdir -p .hypothesis
+           cd .hypothesis
+           mkdir -p examples
+           cd ..
            ./test_ivy_stateful.sh ${{ matrix.backends }} ${{ matrix.submodules }}
+
+       - name: Zip Hypothesis Examples
+         run: |
+           cd ivy/.hypothesis
+           zip -r examples.zip examples
+
+       - name: Upload hypothesis
+         uses: actions/upload-artifact@v3
+         with:
+           name: hypothesis_${{ matrix.backends }}_${{ matrix.submodules }}_zip
+           path: |
+             ivy/.hypothesis/examples.zip
+
+#      - name: Check on failures
+#        if: steps.tests.outcome != 'success'
+#        run: exit 1
